[[media]]
id = "sc-feb-testlaunch"
url = "/src/assets/images/Gallery/sc-feb-testlaunch.jpg"
alt = "2024 Team at Second Test launch Loading the Rocket onto the Pad"

[[media]]
id = "20230619_142255"
url = "/src/assets/images/Gallery/20230619_142255.jpg"
alt = "Hanna, Dawsyn, Binay, and Demetra at Spaceport 2023"

[[media]]
id = "ad-astra"
url = "/src/assets/images/Gallery/ad-astra.jpg"
alt = "Ad Astra mid-flight"

[[media]]
id = "bens-l1"
url = "/src/assets/images/Gallery/bens-l1.jpg"
alt = "Ben mounting L1 Certification Rocket"

[[media]]
id = "BRL04546"
url = "/src/assets/images/Gallery/BRL04546.JPG"
alt = "2024 Team walking rocket to the pad for Second Test Launch"

[[media]]
id = "daniels-l1"
url = "/src/assets/images/Gallery/daniels-l1.jpg"
alt = "Daniel Young posing with his L1"

[[media]]
id = "fins-cutout"
url = "/src/assets/images/Gallery/fins-cutout.jpg"
alt = "Trevor and Jack working on the airframe"

[[media]]
id = "fins-test"
url = "/src/assets/images/Gallery/fins-test.jpg"
alt = "Trevor and Jack preparing to cut down fins"

[[media]]
id = "hanna-l1"
url = "/src/assets/images/Gallery/hanna-l1.jpg"
alt = "Hanna and Dan retrieving an L1 Rocket"

[[media]]
id = "l1-people-2"
url = "/src/assets/images/Gallery/l1-people-2.jpg"
alt = "First L1 Certs of the season"

[[media]]
id = "l1-people"
url = "/src/assets/images/Gallery/l1-people.jpg"
alt = "5 members posing with the successfully certified rockets"

[[media]]
id = "l1-rocket"
url = "/src/assets/images/Gallery/l1-rocket.jpg"
alt = "Hanna's L1 Rocket going to the stars"

[[media]]
id = "michigan"
url = "/src/assets/images/Gallery/michigan.jpg"
alt = "Ben Anderson Integrating Active Drag System for flight"


[[media]]
id = "morgans-l1"
url = "/src/assets/images/Gallery/morgans-l1.jpg"
alt = "Morgan Duty Launching her L1"

[[media]]
id = "team-valkyrie"
url = "/src/assets/images/Gallery/team-valkyrie.jpg"
alt = "2023 Spaceport"

[[media]]
id = "whipsnake"
url = "/src/assets/images/Gallery/whipsnake.jpg"
alt = "Whipsnake at 2018 Spaceport America Launch"